[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.fuzz]
runs = 1000

[profile.test]
block_number = 108376869
block_timestamp = 1692352515