[profile.default]
src = "src"
test = "test/foundry"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
